# bin2h.cmake — embed a file as a C byte array.
# Usage (script mode):
#   cmake -DINPUT=<file> -DOUTPUT=<header> -DSYMBOL=<identifier> -P bin2h.cmake
# Emits: const unsigned char <SYMBOL>[] = {...}; const unsigned int <SYMBOL>Len;

if(NOT INPUT OR NOT OUTPUT OR NOT SYMBOL)
  message(FATAL_ERROR "bin2h.cmake needs -DINPUT, -DOUTPUT, -DSYMBOL")
endif()

file(READ "${INPUT}" HEX_CONTENT HEX)
string(LENGTH "${HEX_CONTENT}" HEX_LEN)
math(EXPR BYTE_LEN "${HEX_LEN} / 2")

# "0xAB, " for every byte, 12 bytes per line.
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1, " BYTES "${HEX_CONTENT}")
string(REGEX REPLACE "((0x[0-9a-f][0-9a-f], ){12})" "\\1\n  " BYTES "${BYTES}")

file(WRITE "${OUTPUT}" "// Generated by bin2h.cmake from ${INPUT} — do not edit.
#pragma once

const unsigned char ${SYMBOL}[] = {
  ${BYTES}
};
const unsigned int ${SYMBOL}Len = ${BYTE_LEN};
")
